# Generated by Django 5.1.1 on 2024-10-12 11:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("credits_amount", models.PositiveSmallIntegerField()),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("GP", "Google Pay"), ("CC", "Credit card")],
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("SS", "Success"),
                            ("CD", "Canceled"),
                        ],
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "transactions",
            },
        ),
    ]
