# Generated by Django 5.1.1 on 2024-10-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="latitude",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="user",
            name="longitude",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="user",
            name="service_price_type",
            field=models.CharField(
                choices=[("PH", "Per hour"), ("PL", "Per lesson")],
                default="PL",
                max_length=2,
            ),
        ),
    ]
