"""make verification admin id nullable

Revision ID: 0495159bef7e
Revises: a13d4eaad344
Create Date: 2025-04-26 09:57:41.068017

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0495159bef7e"
down_revision: Union[str, None] = "a13d4eaad344"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_verifications", "admin_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_verifications", "admin_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
