"""extend user verification model

Revision ID: 1e766569c084
Revises: 265c474c5ffc
Create Date: 2025-04-26 08:41:19.141254

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e766569c084"
down_revision: Union[str, None] = "265c474c5ffc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_verifications",
        sa.Column("id_card_photo", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "user_verifications", sa.Column("about_me_text", sa.Text(), nullable=False)
    )
    op.add_column(
        "user_verifications",
        sa.Column("about_me_video_link", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "user_verifications", sa.Column("service_price", sa.Float(), nullable=False)
    )
    op.add_column(
        "user_verifications",
        sa.Column("service_price_type", sa.String(length=2), nullable=False),
    )
    op.add_column(
        "user_verifications",
        sa.Column("cv_link", sa.String(length=255), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_verifications", "cv_link")
    op.drop_column("user_verifications", "service_price_type")
    op.drop_column("user_verifications", "service_price")
    op.drop_column("user_verifications", "about_me_video_link")
    op.drop_column("user_verifications", "about_me_text")
    op.drop_column("user_verifications", "id_card_photo")
    # ### end Alembic commands ###
