"""extend mentor verification field

Revision ID: 265c474c5ffc
Revises: b1b08347c104
Create Date: 2025-04-24 13:30:02.390496

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "265c474c5ffc"
down_revision: Union[str, None] = "b1b08347c104"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "verification_status",
            sa.String(length=2),
            server_default="UV",
            nullable=False,
        ),
    )
    op.drop_column("users", "is_verified")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "verification_status")
    # ### end Alembic commands ###
