"""add activity categories to verifications

Revision ID: a13d4eaad344
Revises: 1e766569c084
Create Date: 2025-04-26 09:15:59.638648

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a13d4eaad344"
down_revision: Union[str, None] = "1e766569c084"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_verifications",
        sa.Column(
            "activity_categories",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_verifications", "activity_categories")
    # ### end Alembic commands ###
