"""make user full name optional for google auth

Revision ID: b1b08347c104
Revises: f016f9a3f48e
Create Date: 2025-04-09 16:32:21.335618

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1b08347c104"
down_revision: Union[str, None] = "f016f9a3f48e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "name", existing_type=sa.VARCHAR(length=50), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###
