# Generated by Django 5.1.1 on 2024-10-12 11:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityCategoryAdvertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("S", "Seeking"), ("P", "Providing")], max_length=2
                    ),
                ),
            ],
            options={
                "db_table": "activity_categories_advertisements",
            },
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("service_price", models.FloatField(default=0)),
                ("number_of_views", models.PositiveIntegerField(default=0)),
                (
                    "service_type",
                    models.CharField(
                        choices=[("S", "Seeking"), ("P", "Providing")], max_length=2
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "advertisements",
            },
        ),
    ]
