# Generated by Django 5.1.1 on 2024-10-12 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advertisements", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitycategoryadvertisement",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.activitycategory"
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="activitycategoryadvertisement",
            name="advertisement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="advertisements.advertisement",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activitycategoryadvertisement",
            unique_together={("advertisement", "type", "category")},
        ),
    ]
